name: Duplicate Code Check

on:
  pull_request:
    paths: ['students/**']  # Запускается только при изменении файлов в папке students

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed task directory
        id: detect_task
        run: |
          # Находим измененную task_папку
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- students/)
          TASK_DIR=""
          
          for file in $CHANGED_FILES; do
            if [[ $file =~ students/([^/]+)/(task_[^/]+)/ ]]; then
              TASK_DIR="${BASH_REMATCH[2]}"
              break
            fi
          done
          
          if [ -z "$TASK_DIR" ]; then
            echo "No task directory found in changes"
            exit 0
          fi
          
          echo "task_dir=$TASK_DIR" >> $GITHUB_OUTPUT
          echo "Detected task directory: $TASK_DIR"

      - name: Create comparison directories list
        id: create_dirs
        run: |
          # Создаем список директорий для сравнения, исключая your_id
          COMPARE_DIRS=$(find students -type d -name "${{ steps.detect_task.outputs.task_dir }}" | grep -v "students/your_id" | tr '\n' ' ')
          echo "compare_dirs=$COMPARE_DIRS" >> $GITHUB_OUTPUT
          echo "Directories to compare: $COMPARE_DIRS"

      - name: Run Duplicate Code Detection
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "${{ steps.create_dirs.outputs.compare_dirs }}"  # Используем только разрешенные директории
          ignore_below: 20           # Игнорировать сходство ниже 20%
          fail_above: 80             # Завершить с ошибкой при сходстве выше 80%
          warn_above: 20             # Показать предупреждение при сходстве выше 20%
          file_extensions: "js, html, css"  # Проверяемые расширения файлов
          one_comment: true          # Обновлять один комментарий, а не создавать новые